version: "3"
services:
  # my-app:
  #   image: 953288953594.dkr.ecr.ap-south-1.amazonaws.com/my-app:1.4
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - mongoDB
  #   command: ["sh", "-c", "sleep 30 && npm start"]
  #   restart: always
  #   networks:
  #     - my-network

  mongoDB:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - my-network
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_SERVER: mongoDB
    depends_on:
      - mongoDB
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
